version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html

hooks:
  AfterInstall:
    - location: deploy_docker_image.sh
      timeout: 300
      runas: root

# Update with your repository and commit details
repository: https://github.com/shirisha-1910/temp.git
commitId: f54b1f767d7f3285fc0b535712546b3c29371b30
