version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html

hooks:
  AfterInstall:
    - location:  ./temp/scripts/deploy_docker_image.sh
      timeout: 300
      runas: root

