#!/bin/bash

echo "Deploy script started..."
present=$(pwd)
echo "Current location: $present"

echo "Pulling Docker image..."
docker pull sirishassss/new-temp:latest

echo "Stopping and removing existing container..."
docker stop new-temp || true
docker rm new-temp || true

echo "Starting new container..."
docker run -d --name new-temp -p 8080:80 sirishassss/new-temp:latest

echo "Deployment completed."
